Trix.config.lang =
  attachFiles: "Lisää tiedosto tai kuva"
  bold: "Lihavointi"
  bullets: "Luettelo"
  byte:  "Bitti"
  bytes: "Bitits"
  captionPlaceholder: "Lisää otsikko…"
  code: "Koodi"
  heading1: "Otsikko"
  indent: "Kasvata sisennystä"
  italic: "Italic"
  link: "Linkki"
  numbers: "Numeroitu lista"
  outdent: "Vähennä sisennystä"
  quote: "Viittaus"
  redo: "Tee uudelleen"
  remove: "Poista"
  strike: "Läpiviiva"
  undo: "Peruuta"
  unlink: "Poista linkki"
  url: "Osoite"
  urlPlaceholder: "Lisää osoite.…"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
